export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const LOG_OUT = 'LOG_OUT';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_FAIL = "ADD_TODO_FAIL";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const REMOVE_TODO_SUCCESS = "REMOVE_TODO_SUCCESS";
export const REMOVE_TODO_FAIL = "REMOVE_TODO_FAIL";

export const SHOW_ALL = "SHOW_ALL";
export const SHOW_COMPLETED = "SHOW_COMPLETED";
export const SHOW_ACTIVE = "SHOW_ACTIVE";
export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";